---
title: "Análise de dados sobre Séries"
author: "Gileade"
date: "4 de junho de 2017"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align="center")
```

```{r}
library(tidyverse)
library(knitr)
library(htmltools)
library(highcharter)
```

```{r leitura dos dados}
series_imdb <- read_csv("../problema-1/series_from_imdb.csv")
```

```{r}
series_netflix <- series_imdb %>% filter(series_name %in% c("13 Reasons Why", "Daredevil",  "House of Cards", "Narcos", "Sense8", "Stranger Things")) %>%
  mutate(series_name = factor(series_name)) %>%
  mutate(season = factor(season))
```

```{r}
library(ggplot2)
series_netflix %>%
  ggplot(aes(series_ep, UserRating, color = as.factor(season))) +
  geom_line() +
  facet_wrap(~ series_name) +
  labs(x = "Número do episódio", y = "Nota dos usuários", color = "Temporada", title = "Ratings dos episódios por temporada por série")
```

```{r}
map(levels(series_netflix$series_name), function(x){
  series_netflix %>%
    filter(series_name == x) %>% 
    hchart("line", hcaes(x = series_ep, y = UserRating, group = season)) %>%
    hc_add_theme(hc_theme_smpl()) %>% 
    hc_title(text = x) %>%
    hc_xAxis(title = list(text = "Número do episódio"), tickInterval = 10) %>%
    hc_yAxis(title = list(text = "Nota do episódio"), tickInterval = .2, min = 7.5, max = 9.7) %>%
    hc_tooltip(pointFormat = "Nome: {point.Episode} <br> Nota: {point.y} <br> Número de Votos: {point.UserVotes}") %>%
    hc_legend(align = "right", verticalAlign = "top",
            layout = "vertical", x = 0, y = 100)
  }) %>% 
  hw_grid(ncol = 2)  %>% browsable()
```


